// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFRlGSfalp6-npCoF93wMEb9vrWQWERvw',
    appId: '1:765315062014:web:2c5278a2da6f3be332adaf',
    messagingSenderId: '765315062014',
    projectId: 'chatapp-8fdf1',
    authDomain: 'chatapp-8fdf1.firebaseapp.com',
    storageBucket: 'chatapp-8fdf1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPbaB94ZOSCRxCCWwrPyvN7DXKxqs_L98',
    appId: '1:765315062014:android:d90fb35857c3027032adaf',
    messagingSenderId: '765315062014',
    projectId: 'chatapp-8fdf1',
    storageBucket: 'chatapp-8fdf1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjM3uyjVqWHgiViYzA9-QgMz1I6etaV64',
    appId: '1:765315062014:ios:24b6306b247391a532adaf',
    messagingSenderId: '765315062014',
    projectId: 'chatapp-8fdf1',
    storageBucket: 'chatapp-8fdf1.appspot.com',
    iosBundleId: 'com.example.zeroToHero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjM3uyjVqWHgiViYzA9-QgMz1I6etaV64',
    appId: '1:765315062014:ios:24b6306b247391a532adaf',
    messagingSenderId: '765315062014',
    projectId: 'chatapp-8fdf1',
    storageBucket: 'chatapp-8fdf1.appspot.com',
    iosBundleId: 'com.example.zeroToHero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFRlGSfalp6-npCoF93wMEb9vrWQWERvw',
    appId: '1:765315062014:web:f6b249d207f6fa3a32adaf',
    messagingSenderId: '765315062014',
    projectId: 'chatapp-8fdf1',
    authDomain: 'chatapp-8fdf1.firebaseapp.com',
    storageBucket: 'chatapp-8fdf1.appspot.com',
  );
}
